import { Geist, Geist_Mono, Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const karmaticArcade = localFont({
  src: [
    {
      path: "../public/fonts/KarmaticArcade-6Yrp1.ttf",
      weight: "700",
    },
  ],
  variable: "--font-karmatic",
});

const jersey = localFont({
  src: [
    {
      path: "../public/fonts/Jersey20-Regular.ttf",
    },
  ],
  variable: "--font-jersey",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${karmaticArcade.variable} ${jersey.variable} ${inter.className} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
